/**
 * Seed de dados de teste — 5 imobiliárias + 20 imóveis de Caxias do Sul
 * Executar: npm run db:seed
 * Pode ser rodado múltiplas vezes — limpa os dados anteriores automaticamente.
 */

import { config } from "dotenv";
config({ path: ".env.local" });

import { drizzle } from "drizzle-orm/neon-http";
import { neon } from "@neondatabase/serverless";
import * as s from "../lib/db/schema/tenant";

const sql = neon(process.env.DATABASE_URL!);
const db = drizzle(sql);

const now = new Date();

// Imagens de teste via picsum.photos (gratuito, sem API key)
// Cada seed string produz sempre a mesma foto
const img = (seed: string) => `https://picsum.photos/seed/${seed}/800/500`;

async function seed() {
  console.log("🗑️  Limpando dados anteriores...");
  await db.delete(s.imoveis);
  await db.delete(s.fontes);

  console.log("🌱 Inserindo 5 fontes de Caxias do Sul...");

  const [f1, f2, f3, f4, f5] = await db
    .insert(s.fontes)
    .values([
      {
        nome: "Habitare Imóveis",
        url: "https://habitare-imoveis.com.br",
        cidade: "Caxias do Sul",
        estado: "RS",
        status: "ok",
        ativa: true,
        lastCrawl: now,
      },
      {
        nome: "Alles Imóveis",
        url: "https://allesgabrielimoveis.com.br",
        cidade: "Caxias do Sul",
        estado: "RS",
        status: "ok",
        ativa: true,
        lastCrawl: now,
      },
      {
        nome: "Minucci Imóveis",
        url: "https://minucci.com.br",
        cidade: "Caxias do Sul",
        estado: "RS",
        status: "ok",
        ativa: true,
        lastCrawl: now,
      },
      {
        nome: "Becker Negócios Imobiliários",
        url: "https://beckerimoveis.com.br",
        cidade: "Caxias do Sul",
        estado: "RS",
        status: "ok",
        ativa: true,
        lastCrawl: now,
      },
      {
        nome: "Priorim Imóveis",
        url: "https://priorim.com.br",
        cidade: "Caxias do Sul",
        estado: "RS",
        status: "ok",
        ativa: true,
        lastCrawl: now,
      },
    ])
    .returning({ id: s.fontes.id, nome: s.fontes.nome });

  console.log(`✅ Fontes: ${[f1, f2, f3, f4, f5].map((f) => f.nome).join(", ")}`);
  console.log("🌱 Inserindo 20 imóveis...");

  await db.insert(s.imoveis).values([
    // ── Habitare Imóveis (4) ─────────────────────────────────────────────────
    {
      fonteId: f1.id,
      urlAnuncio: "https://habitare-imoveis.com.br/ap001",
      titulo: "Apartamento 2 dormitórios no Centro",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "Centro",
      estado: "RS",
      preco: "285000",
      areaM2: "62",
      quartos: 2,
      banheiros: 1,
      vagas: 1,
      disponivel: true,
      imagens: [img("ap-centro-cxs")],
    },
    {
      fonteId: f1.id,
      urlAnuncio: "https://habitare-imoveis.com.br/ap002",
      titulo: "Apartamento 3 suítes em São Pelegrino",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "São Pelegrino",
      estado: "RS",
      preco: "520000",
      areaM2: "98",
      quartos: 3,
      banheiros: 2,
      vagas: 2,
      disponivel: true,
      imagens: [img("ap-suite-cxs")],
    },
    {
      fonteId: f1.id,
      urlAnuncio: "https://habitare-imoveis.com.br/cs001",
      titulo: "Casa 3 quartos com jardim em Ana Rech",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "Ana Rech",
      estado: "RS",
      preco: "430000",
      areaM2: "140",
      quartos: 3,
      banheiros: 2,
      vagas: 2,
      disponivel: true,
      imagens: [img("casa-jardim-anarech")],
    },
    {
      fonteId: f1.id,
      urlAnuncio: "https://habitare-imoveis.com.br/ap003",
      titulo: "Studio moderno próximo à UCS",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "Petrópolis",
      estado: "RS",
      preco: "185000",
      areaM2: "36",
      quartos: 1,
      banheiros: 1,
      vagas: 0,
      disponivel: true,
      imagens: [img("studio-moderno-cxs")],
    },
    // ── Alles Imóveis (4) ───────────────────────────────────────────────────
    {
      fonteId: f2.id,
      urlAnuncio: "https://allesgabrielimoveis.com.br/cs001",
      titulo: "Casa nova em condomínio fechado",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "Desvio Rizzo",
      estado: "RS",
      preco: "690000",
      areaM2: "190",
      quartos: 4,
      banheiros: 3,
      vagas: 3,
      disponivel: true,
      imagens: [img("casa-condominio-rizzo")],
    },
    {
      fonteId: f2.id,
      urlAnuncio: "https://allesgabrielimoveis.com.br/ap001",
      titulo: "Apartamento alto padrão na Madureira",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "Madureira",
      estado: "RS",
      preco: "780000",
      areaM2: "145",
      quartos: 3,
      banheiros: 3,
      vagas: 2,
      disponivel: true,
      imagens: [img("ap-alto-padrao-madureira")],
    },
    {
      fonteId: f2.id,
      urlAnuncio: "https://allesgabrielimoveis.com.br/tr001",
      titulo: "Terreno 360m² em São Caetano",
      tipo: "Terreno",
      cidade: "Caxias do Sul",
      bairro: "São Caetano",
      estado: "RS",
      preco: "165000",
      areaM2: "360",
      quartos: 0,
      banheiros: 0,
      vagas: 0,
      disponivel: true,
      imagens: [img("terreno-saocaetano-cxs")],
    },
    {
      fonteId: f2.id,
      urlAnuncio: "https://allesgabrielimoveis.com.br/cs002",
      titulo: "Casa 2 quartos em Panazzolo",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "Panazzolo",
      estado: "RS",
      preco: "298000",
      areaM2: "95",
      quartos: 2,
      banheiros: 1,
      vagas: 1,
      disponivel: true,
      imagens: [img("casa-panazzolo-cxs")],
    },
    // ── Minucci Imóveis (4) ─────────────────────────────────────────────────
    {
      fonteId: f3.id,
      urlAnuncio: "https://minucci.com.br/ap001",
      titulo: "Apartamento 2 quartos com varanda gourmet",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "Rio Branco",
      estado: "RS",
      preco: "345000",
      areaM2: "75",
      quartos: 2,
      banheiros: 2,
      vagas: 1,
      disponivel: true,
      imagens: [img("ap-varanda-riobranco")],
    },
    {
      fonteId: f3.id,
      urlAnuncio: "https://minucci.com.br/cs001",
      titulo: "Casa espaçosa em Santa Lúcia",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "Santa Lúcia",
      estado: "RS",
      preco: "560000",
      areaM2: "210",
      quartos: 4,
      banheiros: 2,
      vagas: 2,
      disponivel: true,
      imagens: [img("casa-espacosa-santalucia")],
    },
    {
      fonteId: f3.id,
      urlAnuncio: "https://minucci.com.br/cm001",
      titulo: "Sala comercial no Centro",
      tipo: "Comercial",
      cidade: "Caxias do Sul",
      bairro: "Centro",
      estado: "RS",
      preco: "320000",
      areaM2: "58",
      quartos: 0,
      banheiros: 1,
      vagas: 1,
      disponivel: true,
      imagens: [img("sala-comercial-centro-cxs")],
    },
    {
      fonteId: f3.id,
      urlAnuncio: "https://minucci.com.br/ap002",
      titulo: "Apartamento 1 dormitório para investimento",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "Centro",
      estado: "RS",
      preco: "155000",
      areaM2: "42",
      quartos: 1,
      banheiros: 1,
      vagas: 0,
      disponivel: true,
      imagens: [img("ap-investimento-centro")],
    },
    // ── Becker Negócios (4) ─────────────────────────────────────────────────
    {
      fonteId: f4.id,
      urlAnuncio: "https://beckerimoveis.com.br/cs001",
      titulo: "Casa 3 dormitórios em São José",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "São José",
      estado: "RS",
      preco: "385000",
      areaM2: "115",
      quartos: 3,
      banheiros: 2,
      vagas: 2,
      disponivel: true,
      imagens: [img("casa-saojose-cxs")],
    },
    {
      fonteId: f4.id,
      urlAnuncio: "https://beckerimoveis.com.br/ap001",
      titulo: "Apartamento térreo com pátio privativo",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "São Pelegrino",
      estado: "RS",
      preco: "310000",
      areaM2: "82",
      quartos: 2,
      banheiros: 1,
      vagas: 1,
      disponivel: true,
      imagens: [img("ap-terreo-patio-cxs")],
    },
    {
      fonteId: f4.id,
      urlAnuncio: "https://beckerimoveis.com.br/tr001",
      titulo: "Terreno plano 500m² em Ana Rech",
      tipo: "Terreno",
      cidade: "Caxias do Sul",
      bairro: "Ana Rech",
      estado: "RS",
      preco: "220000",
      areaM2: "500",
      quartos: 0,
      banheiros: 0,
      vagas: 0,
      disponivel: true,
      imagens: [img("terreno-anarech-cxs")],
    },
    {
      fonteId: f4.id,
      urlAnuncio: "https://beckerimoveis.com.br/cs002",
      titulo: "Casa nova 4 dormitórios com suíte",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "Petrópolis",
      estado: "RS",
      preco: "620000",
      areaM2: "175",
      quartos: 4,
      banheiros: 3,
      vagas: 2,
      disponivel: true,
      imagens: [img("casa-suite-petropolis")],
    },
    // ── Priorim Imóveis (4) ─────────────────────────────────────────────────
    {
      fonteId: f5.id,
      urlAnuncio: "https://priorim.com.br/ap001",
      titulo: "Apartamento 2 quartos no Esplanada",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "Esplanada",
      estado: "RS",
      preco: "265000",
      areaM2: "68",
      quartos: 2,
      banheiros: 1,
      vagas: 1,
      disponivel: true,
      imagens: [img("ap-esplanada-cxs")],
    },
    {
      fonteId: f5.id,
      urlAnuncio: "https://priorim.com.br/cs001",
      titulo: "Sobrado 3 dormitórios com quintal",
      tipo: "Casa",
      cidade: "Caxias do Sul",
      bairro: "Kayser",
      estado: "RS",
      preco: "480000",
      areaM2: "160",
      quartos: 3,
      banheiros: 2,
      vagas: 2,
      disponivel: true,
      imagens: [img("sobrado-quintal-kayser")],
    },
    {
      fonteId: f5.id,
      urlAnuncio: "https://priorim.com.br/ap002",
      titulo: "Cobertura duplex com vista panorâmica",
      tipo: "Apartamento",
      cidade: "Caxias do Sul",
      bairro: "São Pelegrino",
      estado: "RS",
      preco: "850000",
      areaM2: "220",
      quartos: 3,
      banheiros: 3,
      vagas: 3,
      disponivel: true,
      imagens: [img("cobertura-duplex-saopelegrino")],
    },
    {
      fonteId: f5.id,
      urlAnuncio: "https://priorim.com.br/cm001",
      titulo: "Galpão comercial 400m² no Cruzeiro",
      tipo: "Comercial",
      cidade: "Caxias do Sul",
      bairro: "Cruzeiro",
      estado: "RS",
      preco: "890000",
      areaM2: "400",
      quartos: 0,
      banheiros: 2,
      vagas: 8,
      disponivel: true,
      imagens: [img("galpao-cruzeiro-cxs")],
    },
  ]);

  console.log("✅ 20 imóveis inseridos");
  console.log("\n🎉 Seed concluído! 5 fontes + 20 imóveis de Caxias do Sul prontos para teste.");
}

seed().catch(console.error).finally(() => process.exit(0));
